# Generated by Django 4.1.1 on 2022-09-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyLocationModel',
        ),
    ]
